server:
  port: 8082
  servlet:
    context-path: /api
spring:
    datasource:
      url: jdbc:mysql://[Your Database Url]/housing_lease_db?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      password: [Your password]
      username: [Your Account]
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
    mvc:
      path match:
        matching-strategy: ant_path_matcher

mybatis-plus:
  type-handlers-package: com.web.platform.handler

logging:
  level:
    mybatis: info
    com.web.platform: info
  config:
    classpath:log4j2.xml
